### ISSUE TITLE
 CMake Error: Could not create named generator -B/home/marcel/CLionProjects/TgCCore-build/Release

### ISSUE THREAD

**Issue by nitanmarcel** [siegelaaron94/atom-build-cmake#48]
I'm trying to build a release from my library but I'm getting this error: `
CMake Error: Could not create named generator -B/home/marcel/CLionProjects/TgCCore-build/Release` what does this mean?

**Comment by VivienMrclt** [comment]
This is due to a problem in the command generation I guess. I'm having the same issue. The command executed to build debug is 
```bash
cmake -G -BSome/Path
```
The problem is that there is no argument for the parameter `G`. Thus cmake reads what's following. But the `-BSome/Path` is not the name of a generator. 
I don't understand what this the executed command.

**Comment by nitanmarcel** [comment]
> This is due to a problem in the command generation I guess. I'm having the same issue. The command executed to build debug is
> 
> ```shell
> cmake -G -BSome/Path
> ```
> 
> The problem is that there is no argument for the parameter `G`. Thus cmake reads what's following. But the `-BSome/Path` is not the name of a generator.
> I don't understand what this the executed command.

Thanks. But I fixed it by editing the regex which if I remember right it messed up the command detection. Well it's been a long time since I used CLion so I better close this as I don't need help with a fix for the moment :)

Thanks for your answer
